<<<<<<< HEAD
# Generated by Django 3.2.25 on 2024-07-07 06:23
=======
# Generated by Django 3.2.25 on 2024-07-05 09:36
>>>>>>> authentications-api

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('accounts', '0002_alter_profile_image'),
=======
        ("accounts", "0002_alter_profile_image"),
>>>>>>> authentications-api
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='user',
            name='is_verified',
=======
            model_name="user",
            name="is_verified",
>>>>>>> authentications-api
            field=models.BooleanField(default=False),
        ),
    ]
